<?php
require_once __DIR__ . '/includes/config.php';
require_once __DIR__ . '/includes/session.php';
if (session_status() === PHP_SESSION_NONE) session_start();
if (empty($_SESSION['user_id'])) { header('Location: login.php'); exit; }
$userId = (int)$_SESSION['user_id'];

$stmt = $conn->prepare("SELECT r.id, r.name, r.image, r.address, r.rating, r.delivery_time, r.delivery_fee, f.created_at FROM restaurant_favorites f INNER JOIN restaurants r ON r.id=f.restaurant_id WHERE f.user_id=? AND r.status=1 ORDER BY f.created_at DESC");
$stmt->bind_param('i', $userId); $stmt->execute(); $result=$stmt->get_result();
$restaurants=[]; while($row=$result->fetch_assoc()) $restaurants[]=$row; $stmt->close();
function fh($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Favourite Restaurants - Humsafar</title><link rel="stylesheet" href="css/style.css"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"><style>
body{margin:0;background:#f6f7f9;font-family:Segoe UI,Arial,sans-serif;color:#222}.wrap{max-width:1100px;margin:35px auto;padding:0 20px 60px}.head{display:flex;justify-content:space-between;align-items:center;margin-bottom:22px}.head h1{margin:0;color:#ed0038}.head a{color:#ed0038;text-decoration:none;font-weight:700}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.card{background:#fff;border:1px solid #eee;border-radius:16px;overflow:hidden;box-shadow:0 7px 24px rgba(0,0,0,.05)}.img{height:170px;background:#fff1f5}.img img{width:100%;height:100%;object-fit:cover}.body{padding:16px}.body h3{margin:0 0 7px}.muted{color:#777;font-size:12px;margin:5px 0}.actions{display:flex;gap:8px;margin-top:14px}.btn{flex:1;text-align:center;padding:10px;border-radius:9px;text-decoration:none;font-weight:700;font-size:12px;background:#ed0038;color:#fff}.btn.alt{background:#fff;color:#ed0038;border:1px solid #ed0038}.empty{text-align:center;background:#fff;border-radius:16px;padding:50px;color:#777}@media(max-width:800px){.grid{grid-template-columns:1fr 1fr}}@media(max-width:520px){.grid{grid-template-columns:1fr}}
</style></head><body><div class="wrap"><div class="head"><div><h1>❤️ Favourite Restaurants</h1><div class="muted">Your saved restaurants</div></div><a href="index.php">← Browse Restaurants</a></div>
<?php if(!$restaurants): ?><div class="empty"><h2>No favourites yet</h2><p>Open a restaurant and tap the heart to save it here.</p><a class="btn" href="restaurants.php">Find Restaurants</a></div><?php else: ?><div class="grid"><?php foreach($restaurants as $r): $img=trim((string)$r['image']); $src=$img===''?'assets/images/restaurant-placeholder.jpg':(preg_match('/^(https?:\/\/|\/|data:)/i',$img)?$img:(strpos($img,'assets/')===0?$img:'assets/images/restaurants/'.basename($img))); ?><div class="card"><div class="img"><img src="<?=fh($src)?>" alt="<?=fh($r['name'])?>" onerror="this.style.display='none'"></div><div class="body"><h3><?=fh($r['name'])?></h3><div class="muted">⭐ <?=number_format((float)$r['rating'],1)?> · <?=fh($r['delivery_time'] ?: 'Delivery available')?></div><div class="muted">📍 <?=fh($r['address'])?></div><div class="actions"><a class="btn" href="restaurant.php?id=<?=(int)$r['id']?>">Open</a><a class="btn alt" href="favorite_restaurant.php?restaurant_id=<?=(int)$r['id']?>&action=remove">Remove</a></div></div></div><?php endforeach; ?></div><?php endif; ?></div></body></html>