<?php
require_once __DIR__ . '/includes/config.php';
require_once __DIR__ . '/includes/session.php';
if(session_status()===PHP_SESSION_NONE)session_start();
if(empty($_SESSION['user_id'])){header('Location: login.php');exit;}
$userId=(int)$_SESSION['user_id'];
if(isset($_GET['read'])){$id=(int)$_GET['read'];if($id>0){$s=$conn->prepare('UPDATE customer_notifications SET is_read=1 WHERE id=? AND user_id=?');$s->bind_param('ii',$id,$userId);$s->execute();$s->close();}}
if(isset($_GET['read_all'])){$s=$conn->prepare('UPDATE customer_notifications SET is_read=1 WHERE user_id=?');$s->bind_param('i',$userId);$s->execute();$s->close();}
$s=$conn->prepare('SELECT id,order_id,type,title,message,is_read,created_at FROM customer_notifications WHERE user_id=? ORDER BY id DESC LIMIT 100');$s->bind_param('i',$userId);$s->execute();$rs=$s->get_result();$items=[];while($r=$rs->fetch_assoc())$items[]=$r;$s->close();
$unread=0;foreach($items as $n)$unread+=(int)!$n['is_read'];function nh($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Notifications - Humsafar</title><style>body{margin:0;background:#f6f7f9;font-family:Segoe UI,Arial;color:#222}.wrap{max-width:850px;margin:35px auto;padding:0 20px 60px}.head{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}.head h1{margin:0;color:#ed0038}.head a{color:#ed0038;text-decoration:none;font-weight:700}.notice{background:#fff;border:1px solid #eee;border-radius:14px;padding:17px 20px;margin-bottom:10px;box-shadow:0 5px 18px rgba(0,0,0,.04)}.notice.unread{border-left:4px solid #ed0038;background:#fff9fb}.top{display:flex;justify-content:space-between;gap:15px}.title{font-weight:800}.time{color:#999;font-size:11px;white-space:nowrap}.message{color:#666;font-size:13px;margin:7px 0}.action{font-size:11px;color:#ed0038;text-decoration:none;font-weight:800}.empty{background:#fff;padding:50px;text-align:center;border-radius:15px;color:#777}.badge{display:inline-block;background:#ed0038;color:#fff;border-radius:20px;padding:4px 9px;font-size:11px}</style></head><body><div class="wrap"><div class="head"><div><h1>🔔 Notifications</h1><?php if($unread):?><span class="badge"><?=$unread?> unread</span><?php endif;?></div><div><a href="index.php">Home</a> &nbsp; <a href="notifications.php?read_all=1">Mark all read</a></div></div><?php if(!$items):?><div class="empty"><h2>No notifications</h2><p>Order updates and important messages will appear here.</p></div><?php else:foreach($items as $n):?><div class="notice <?=!(int)$n['is_read']?'unread':''?>"><div class="top"><div class="title"><?=nh($n['title'])?></div><div class="time"><?=nh(date('d M Y, h:i A',strtotime($n['created_at'])))?></div></div><div class="message"><?=nh($n['message'])?></div><?php if((int)$n['order_id']>0):?><a class="action" href="track-order.php?order_id=<?=(int)$n['order_id']?>">View Order</a><?php endif;?><?php if(!(int)$n['is_read']):?> &nbsp; <a class="action" href="notifications.php?read=<?=(int)$n['id']?>">Mark read</a><?php endif;?></div><?php endforeach;endif;?></div></body></html>