<?php
require_once __DIR__ . '/includes/config.php';
require_once __DIR__ . '/includes/session.php';
if(session_status()===PHP_SESSION_NONE)session_start();
if(empty($_SESSION['user_id'])){header('Location: login.php');exit;}
$userId=(int)$_SESSION['user_id'];$orderId=(int)($_GET['order_id']??$_POST['order_id']??0);
function rh($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
$o=$conn->prepare("SELECT o.id,o.restaurant_id,o.order_number,o.order_status,r.name AS restaurant_name FROM orders o INNER JOIN restaurants r ON r.id=o.restaurant_id WHERE o.id=? AND o.user_id=? AND o.order_status IN('delivered','completed') LIMIT 1");$o->bind_param('ii',$orderId,$userId);$o->execute();$order=$o->get_result()->fetch_assoc();$o->close();
if(!$order){http_response_code(404);die('Only your delivered orders can be reviewed.');}
$message='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){$rating=(int)($_POST['rating']??0);$comment=trim((string)($_POST['comment']??''));if($rating<1||$rating>5)$error='Please select a rating from 1 to 5.';elseif(mb_strlen($comment)>1000)$error='Review is too long.';else{$s=$conn->prepare('INSERT INTO restaurant_reviews(user_id,restaurant_id,order_id,rating,comment) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE rating=VALUES(rating),comment=VALUES(comment),updated_at=CURRENT_TIMESTAMP');$rid=(int)$order['restaurant_id'];$s->bind_param('iiiis',$userId,$rid,$orderId,$rating,$comment);if($s->execute()){$message='Your review has been saved. Thank you!';}else{$error='Unable to save your review.';}$s->close();}}
$current=0;$s=$conn->prepare('SELECT rating,comment FROM restaurant_reviews WHERE user_id=? AND order_id=? LIMIT 1');$s->bind_param('ii',$userId,$orderId);$s->execute();$current=$s->get_result()->fetch_assoc()?:[];$s->close();
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Rate Order - Humsafar</title><style>body{margin:0;background:#f6f7f9;font-family:Segoe UI,Arial;color:#222}.box{max-width:650px;margin:50px auto;padding:30px;background:#fff;border-radius:18px;box-shadow:0 10px 35px rgba(0,0,0,.07)}h1{color:#ed0038}.stars{display:flex;gap:7px;margin:18px 0}.stars input{display:none}.stars label{font-size:34px;color:#ccc;cursor:pointer}.stars label:hover,.stars input:checked+label{color:#f6b800}textarea{width:100%;min-height:130px;padding:12px;box-sizing:border-box;border:1px solid #ddd;border-radius:10px;resize:vertical}.btn{border:0;background:#ed0038;color:#fff;padding:12px 20px;border-radius:9px;font-weight:800;cursor:pointer}.msg{padding:12px;border-radius:8px;background:#e9f8ef;color:#168249}.err{padding:12px;border-radius:8px;background:#ffebed;color:#c22}.back{display:inline-block;margin-top:18px;color:#ed0038;text-decoration:none;font-weight:700}</style></head><body><div class="box"><h1>⭐ Rate <?=rh($order['restaurant_name'])?></h1><p>Order <?=rh($order['order_number'])?></p><?php if($message):?><div class="msg"><?=rh($message)?></div><?php endif;?><?php if($error):?><div class="err"><?=rh($error)?></div><?php endif;?><form method="post"><input type="hidden" name="order_id" value="<?=$orderId?>"><strong>Your rating</strong><div class="stars"><?php for($i=5;$i>=1;$i--):?><input id="s<?=$i?>" type="radio" name="rating" value="<?=$i?>" <?=((int)($current['rating']??0)===$i?'checked':'')?>><label for="s<?=$i?>">★</label><?php endfor;?></div><label><strong>Your review</strong></label><textarea name="comment" maxlength="1000" placeholder="How was your food and delivery?"><?=rh($current['comment']??'')?></textarea><br><br><button class="btn" type="submit">Save Review</button></form><a class="back" href="my_orders.php">← Back to My Orders</a></div></body></html>