<?php
session_start();
require_once '../includes/config.php';
if (empty($_SESSION['rider_logged_in']) || $_SESSION['rider_logged_in'] !== true) { header('Location:rider-login.php'); exit; }
$riderId=(int)($_SESSION['rider_id']??0); if($riderId<1){session_destroy();header('Location:rider-login.php');exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function notifyCustomer($db,$uid,$title,$message,$type,$oid){$s=$db->prepare("INSERT INTO notifications(user_id,role,title,message,type,reference_id) VALUES(?,'customer',?,?,?,?)");if($s){$s->bind_param('isssi',$uid,$title,$message,$type,$oid);$s->execute();$s->close();}}
function addHistory($db,$oid,$status,$riderId,$note){$s=$db->prepare("INSERT INTO order_status_history(order_id,status,changed_by,changed_by_role,note) VALUES(?,?,?,'delivery',?)");if($s){$s->bind_param('iiss',$oid,$status,$riderId,$note);$s->execute();$s->close();}}
$s=$conn->prepare('SELECT full_name,phone,vehicle_type,bike_number,status,availability_status FROM riders WHERE id=? LIMIT 1');$s->bind_param('i',$riderId);$s->execute();$r=$s->get_result()->fetch_assoc();$s->close();
$approved=strtolower((string)($r['status']??''))==='active';$msg='';$type='';
if($_SERVER['REQUEST_METHOD']==='POST'&&isset($_POST['delivery_action'])){
 $action=$_POST['delivery_action'];$oid=(int)($_POST['order_id']??0);$conn->begin_transaction();
 try{
  if(!$approved)throw new Exception('Your rider account is not approved yet.');
  if(!$oid||!in_array($action,['accept','picked_up','on_the_way','delivered'],true))throw new Exception('Invalid delivery request.');
  $s=$conn->prepare('SELECT * FROM orders WHERE id=? LIMIT 1 FOR UPDATE');$s->bind_param('i',$oid);$s->execute();$o=$s->get_result()->fetch_assoc();$s->close();if(!$o)throw new Exception('Order not found.');
  $cur=strtolower(trim($o['order_status']));$assigned=(int)$o['rider_id'];
  if($action==='accept'){
   if($cur!=='preparing')throw new Exception('Only Preparing orders can be accepted.');if($assigned&&$assigned!==$riderId)throw new Exception('This order was already accepted by another rider.');
   $s=$conn->prepare("UPDATE orders SET rider_id=?,order_status='rider_assigned' WHERE id=? AND (rider_id IS NULL OR rider_id=0) AND order_status='preparing'");$s->bind_param('ii',$riderId,$oid);$s->execute();if($s->affected_rows!==1)throw new Exception('This order was already taken.');$s->close();
   $s=$conn->prepare("INSERT INTO rider_deliveries(rider_id,order_id,status,assigned_at,accepted_at) VALUES(?,?, 'accepted',NOW(),NOW()) ON DUPLICATE KEY UPDATE status='accepted',accepted_at=NOW()");$s->bind_param('ii',$riderId,$oid);$s->execute();$s->close();
   addHistory($conn,$oid,'rider_assigned',$riderId,'Rider accepted delivery.');notifyCustomer($conn,(int)$o['user_id'],'Rider assigned','A rider has accepted order #'.$oid.'. Rider information and live location are now available.','rider_assigned',$oid);$msg='Delivery accepted.';
   $s=$conn->prepare("UPDATE riders SET availability_status='busy' WHERE id=?");$s->bind_param('i',$riderId);$s->execute();$s->close();
  }else{
   if($assigned!==$riderId)throw new Exception('This order is not assigned to you.');
   if($action==='picked_up'){
    if($cur!=='rider_assigned')throw new Exception('Order must be Rider Assigned first.');$new='picked_up';$rd='picked_up';$note='Rider picked up the order.';$title='Order picked up';$body='Your order #'.$oid.' has been picked up by the rider.';$nt='order_picked_up';
    $s=$conn->prepare("UPDATE orders SET order_status=? WHERE id=? AND rider_id=?");$s->bind_param('sii',$new,$oid,$riderId);$s->execute();$s->close();$s=$conn->prepare("UPDATE rider_deliveries SET status=?,picked_up_at=NOW() WHERE rider_id=? AND order_id=?");$s->bind_param('sii',$rd,$riderId,$oid);$s->execute();$s->close();addHistory($conn,$oid,$new,$riderId,$note);notifyCustomer($conn,(int)$o['user_id'],$title,$body,$nt,$oid);$msg='Order marked as Picked Up.';
   }elseif($action==='on_the_way'){
    if($cur!=='picked_up')throw new Exception('Pick up the order before starting delivery.');$new='on_the_way';$note='Rider started delivery.';$title='Order is on the way';$body='Your order #'.$oid.' is now out for delivery.';$nt='out_for_delivery';
    $s=$conn->prepare("UPDATE orders SET order_status=? WHERE id=? AND rider_id=?");$s->bind_param('sii',$new,$oid,$riderId);$s->execute();$s->close();$s=$conn->prepare("UPDATE rider_deliveries SET status=?,started_at=NOW() WHERE rider_id=? AND order_id=?");$s->bind_param('sii',$new,$riderId,$oid);$s->execute();$s->close();addHistory($conn,$oid,$new,$riderId,$note);notifyCustomer($conn,(int)$o['user_id'],$title,$body,$nt,$oid);$msg='Order is now On The Way.';
   }else{
    if(!in_array($cur,['on_the_way','picked_up'],true))throw new Exception('Order is not ready to be delivered.');$new='delivered';
    $s=$conn->prepare("UPDATE orders SET order_status=? WHERE id=? AND rider_id=?");$s->bind_param('sii',$new,$oid,$riderId);$s->execute();$s->close();$s=$conn->prepare("UPDATE rider_deliveries SET status=?,delivered_at=NOW() WHERE rider_id=? AND order_id=?");$s->bind_param('sii',$new,$riderId,$oid);$s->execute();$s->close();addHistory($conn,$oid,$new,$riderId,'Rider completed delivery.');notifyCustomer($conn,(int)$o['user_id'],'Order delivered','Your order #'.$oid.' has been delivered successfully.','delivered',$oid);$s=$conn->prepare("UPDATE riders SET availability_status='available' WHERE id=?");$s->bind_param('i',$riderId);$s->execute();$s->close();$msg='Order marked as Delivered.';
   }
  }
  $conn->commit();$type='success';
 }catch(Throwable $e){$conn->rollback();$msg=$e->getMessage();$type='error';}
}
if(($_GET['ajax']??'')==='location'&&$_SERVER['REQUEST_METHOD']==='POST'){
 header('Content-Type:application/json');$lat=filter_var($_POST['latitude']??null,FILTER_VALIDATE_FLOAT);$lng=filter_var($_POST['longitude']??null,FILTER_VALIDATE_FLOAT);$acc=filter_var($_POST['accuracy']??null,FILTER_VALIDATE_FLOAT);
 if($lat===false||$lng===false||$lat<-90||$lat>90||$lng<-180||$lng>180){echo json_encode(['ok'=>false]);exit;}$s=$conn->prepare('INSERT INTO rider_locations(rider_id,latitude,longitude,accuracy) VALUES(?,?,?,?)');$s->bind_param('iddd',$riderId,$lat,$lng,$acc);$ok=$s->execute();$s->close();echo json_encode(['ok'=>$ok]);exit;
}
$available=[];$s=$conn->prepare("SELECT o.*,u.full_name customer_name,u.phone customer_phone FROM orders o LEFT JOIN users u ON u.id=o.user_id WHERE o.order_status='preparing' AND (o.rider_id IS NULL OR o.rider_id=0) ORDER BY o.id DESC");$s->execute();$rs=$s->get_result();while($x=$rs->fetch_assoc())$available[]=$x;$s->close();
$active=[];$s=$conn->prepare("SELECT o.*,u.full_name customer_name,u.phone customer_phone FROM orders o LEFT JOIN users u ON u.id=o.user_id WHERE o.rider_id=? AND o.order_status IN('rider_assigned','picked_up','on_the_way') ORDER BY o.id DESC");$s->bind_param('i',$riderId);$s->execute();$rs=$s->get_result();while($x=$rs->fetch_assoc())$active[]=$x;$s->close();
$done=[];$s=$conn->prepare("SELECT o.*,u.full_name customer_name FROM orders o LEFT JOIN users u ON u.id=o.user_id WHERE o.rider_id=? AND o.order_status='delivered' ORDER BY o.id DESC LIMIT 30");$s->bind_param('i',$riderId);$s->execute();$rs=$s->get_result();while($x=$rs->fetch_assoc())$done[]=$x;$s->close();
function sl($s){return ucwords(str_replace('_',' ',strtolower((string)$s)));}
function nextAction($s){if($s==='rider_assigned')return ['picked_up','Picked Up'];if($s==='picked_up')return ['on_the_way','On The Way'];if($s==='on_the_way')return ['delivered','Delivered'];return null;}
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Rider Orders | Humsafar</title><style>body{margin:0;background:#f6f7f9;font-family:Arial,sans-serif;color:#222}.page{margin-left:220px;padding:30px;min-height:100vh}.top{display:flex;justify-content:space-between;align-items:center}.profile,.card,.stat,.empty{background:#fff;border:1px solid #e5e5e5;border-radius:14px}.profile{padding:12px 16px}.profile small{display:block;color:#777;margin-top:4px}.flash{padding:14px;border-radius:10px;margin:18px 0;font-weight:bold}.success{background:#e9f8ee;color:#176b35}.error{background:#fff0f3;color:#a5002d}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin:25px 0}.stat{padding:18px}.stat small{color:#777}.stat strong{display:block;font-size:26px;margin-top:5px}.section{margin:28px 0}.card{margin:14px 0;overflow:hidden}.head{padding:17px 20px;border-bottom:1px solid #eee;display:flex;justify-content:space-between}.body{padding:20px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.box{background:#fafafa;border:1px solid #eee;border-radius:10px;padding:12px}.box small{display:block;color:#888;font-size:11px}.box b{display:block;margin-top:4px}.badge{padding:7px 11px;background:#fff0f5;color:#d00037;border-radius:20px;font-size:12px;font-weight:bold}.btn{border:0;border-radius:9px;padding:11px 16px;font-weight:bold;cursor:pointer;margin-top:15px}.accept{background:#ef003c;color:#fff}.next{background:#eaf5ff;color:#086a9d}.deliver{background:#e9f8ee;color:#176b35}.gps{margin-top:15px;padding:12px;background:#f3f9ff;border:1px solid #d9eafa;border-radius:10px;color:#476675}.empty{padding:40px;text-align:center;color:#888}@media(max-width:800px){.page{margin-left:0;padding:18px}.grid,.stats{grid-template-columns:1fr}.profile{display:none}}</style></head><body><?php if(file_exists(__DIR__.'/rider-sidebar.php'))include __DIR__.'/rider-sidebar.php'; ?><main class="page"><div class="top"><div><small style="color:#ef003c;font-weight:bold">DELIVERY PARTNER</small><h1>Rider Orders</h1><p style="color:#777">Manage your assigned deliveries and live location.</p></div><div class="profile"><b><?=h($r['full_name']??'Rider')?></b><small><?=h(sl($r['status']??''))?> · <?=h(sl($r['availability_status']??''))?></small></div></div><?php if($msg):?><div class="flash <?=h($type)?>"><?=h($msg)?></div><?php endif;?><div class="stats"><div class="stat"><small>New Deliveries</small><strong><?=count($available)?></strong></div><div class="stat"><small>Active</small><strong><?=count($active)?></strong></div><div class="stat"><small>Completed</small><strong><?=count($done)?></strong></div></div>
<section class="section"><h2>New Deliveries</h2><?php if(!$approved):?><div class="empty">Your rider account must be active before accepting deliveries.</div><?php elseif(!$available):?><div class="empty">No new deliveries right now.</div><?php else:foreach($available as $o):?><article class="card"><div class="head"><b>Order #<?=h($o['order_number'])?></b><span class="badge">Preparing</span></div><div class="body"><div class="grid"><div class="box"><small>Customer</small><b><?=h($o['customer_name']??'Customer')?></b></div><div class="box"><small>Phone</small><b><?=h($o['customer_phone']??'')?></b></div><div class="box"><small>Total</small><b>Rs <?=number_format((float)$o['total'],0)?></b></div></div><form method="post"><input type="hidden" name="order_id" value="<?=h($o['id'])?>"><input type="hidden" name="delivery_action" value="accept"><button class="btn accept">Accept Delivery</button></form></div></article><?php endforeach;endif;?></section>
<section class="section"><h2>Active Deliveries</h2><?php if(!$active):?><div class="empty">No active delivery.</div><?php else:foreach($active as $o):$a=nextAction(strtolower($o['order_status']));?><article class="card"><div class="head"><b>Order #<?=h($o['order_number'])?></b><span class="badge"><?=h(sl($o['order_status']))?></span></div><div class="body"><div class="grid"><div class="box"><small>Customer</small><b><?=h($o['customer_name']??'Customer')?></b></div><div class="box"><small>Phone</small><b><?=h($o['customer_phone']??'')?></b></div><div class="box"><small>Delivery Fee</small><b>Rs <?=number_format((float)$o['delivery_fee'],0)?></b></div></div><?php if($a):?><form method="post"><input type="hidden" name="order_id" value="<?=h($o['id'])?>"><input type="hidden" name="delivery_action" value="<?=h($a[0])?>"><button class="btn <?=($a[0]==='delivered'?'deliver':'next')?>"><?=h($a[1])?></button></form><?php endif;?><div class="gps">📍 <b>Live GPS:</b> <span id="gps">Waiting for location permission…</span><br><small>Keep this page open during delivery. Customer tracking refreshes automatically.</small></div></div></article><?php endforeach;endif;?></section>
<section class="section"><h2>Completed Deliveries</h2><?php if(!$done):?><div class="empty">No completed deliveries yet.</div><?php else:foreach($done as $o):?><article class="card"><div class="body"><b>Order #<?=h($o['order_number'])?></b> · <?=h($o['customer_name']??'Customer')?> · Rs <?=number_format((float)$o['delivery_fee'],0)?></div></article><?php endforeach;endif;?></section></main><script>(function(){const active=<?=json_encode(count($active)>0)?>,el=document.getElementById('gps');if(!active){if(el)el.textContent='No active delivery.';return}if(!navigator.geolocation){if(el)el.textContent='GPS not supported.';return}function send(p){const f=new FormData();f.append('latitude',p.coords.latitude);f.append('longitude',p.coords.longitude);f.append('accuracy',p.coords.accuracy||'');fetch('rider-orders.php?ajax=location',{method:'POST',body:f,cache:'no-store'}).then(r=>r.json()).then(x=>{if(el)el.textContent=x.ok?'Live location updated':'Location save failed'}).catch(()=>{if(el)el.textContent='Location update failed'})}function err(){if(el)el.textContent='Allow GPS permission to share live location.'}navigator.geolocation.getCurrentPosition(send,err,{enableHighAccuracy:true,timeout:10000,maximumAge:5000});setInterval(()=>navigator.geolocation.getCurrentPosition(send,err,{enableHighAccuracy:true,timeout:10000,maximumAge:5000}),5000)})();</script></body></html>