<?php
if(session_status()===PHP_SESSION_NONE)session_start();
if(!isset($conn))require_once __DIR__.'/../includes/config.php';
$riderId=(int)($_SESSION['rider_id']??0);$riderName=$_SESSION['rider_name']??'Rider';$riderStatus=strtolower(trim((string)($_SESSION['rider_status']??'pending')));
if($riderId&&isset($conn)&&$conn){$q=$conn->prepare('SELECT full_name,status FROM riders WHERE id=? LIMIT 1');if($q){$q->bind_param('i',$riderId);$q->execute();$r=$q->get_result()->fetch_assoc();$q->close();if($r){$riderName=$r['full_name']?:$riderName;$riderStatus=strtolower(trim($r['status']));$_SESSION['rider_name']=$riderName;$_SESSION['rider_status']=$riderStatus;}}}
$isApproved=in_array($riderStatus,['approved','active'],true);$current=basename($_SERVER['PHP_SELF']);function riderActive($p){global $current;return $current===$p?'active':'';}function rider_e($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}$np=preg_split('/\s+/',trim($riderName));$initials=strtoupper(substr($np[0]??'R',0,1)).(!empty($np[1])?strtoupper(substr($np[1],0,1)):'');
?>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"><style>
.rider-sidebar{position:fixed;top:0;left:0;width:223px;height:100vh;background:#ed0038;color:#fff;display:flex;flex-direction:column;z-index:9999;overflow:hidden}.rider-sidebar-brand{height:96px;padding:0 14px;display:flex;align-items:center;gap:10px;border-bottom:1px solid rgba(255,255,255,.14)}.rider-sidebar-brand-icon{width:44px;height:44px;border-radius:11px;background:#fff;color:#ed0038;display:flex;align-items:center;justify-content:center}.rider-sidebar-brand-name{font-size:22px;font-weight:800}.rider-sidebar-brand-subtitle{margin-top:5px;font-size:8px;font-weight:800;letter-spacing:.55px;color:rgba(255,255,255,.8)}.rider-sidebar-nav{flex:1;padding:18px 12px 8px;overflow-y:auto}.rider-sidebar-section{margin:9px 11px 10px;color:rgba(255,255,255,.78);font-size:10px;font-weight:800;letter-spacing:1px}.rider-sidebar-item{width:100%;min-height:45px;margin-bottom:4px;padding:0 13px;display:flex;align-items:center;gap:12px;border-radius:9px;color:#fff;text-decoration:none;font-size:14px;font-weight:700;box-sizing:border-box}.rider-sidebar-item i:first-child{width:19px;text-align:center}.rider-sidebar-item:hover{background:rgba(255,255,255,.12)}.rider-sidebar-item.active{background:#fff;color:#ed0038}.rider-sidebar-item.active i:first-child{color:#ed0038}.rider-sidebar-item.locked{opacity:.55}.rider-sidebar-lock{margin-left:auto}.rider-sidebar-bottom{padding:10px 11px 11px;border-top:1px solid rgba(255,255,255,.14)}.rider-sidebar-profile{min-height:61px;padding:9px 10px;border-radius:10px;background:rgba(190,0,45,.55);display:flex;align-items:center;gap:9px}.rider-sidebar-avatar{width:37px;height:37px;border-radius:50%;background:#ffd900;color:#111;display:flex;align-items:center;justify-content:center;font-size:12px;font-weight:900}.rider-sidebar-profile-info{min-width:0}.rider-sidebar-profile-name{font-size:10px;font-weight:800;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.rider-sidebar-profile-status{margin-top:4px;color:rgba(255,255,255,.75);font-size:9px;font-weight:700;text-transform:uppercase}.rider-sidebar-logout{margin-top:8px!important;background:rgba(0,0,0,.12)}.rider-sidebar-logout:hover{background:#fff;color:#ed0038}.rider-sidebar-menu{display:none;position:fixed;top:15px;left:15px;width:40px;height:40px;border:0;border-radius:8px;background:#ed0038;color:#fff;z-index:10000}@media(max-width:900px){.rider-sidebar{transform:translateX(-100%);transition:transform .25s}.rider-sidebar.open{transform:translateX(0)}.rider-sidebar-menu{display:flex;align-items:center;justify-content:center}}
</style>
<button type="button" class="rider-sidebar-menu" id="riderSidebarMenu"><i class="fas fa-bars"></i></button><aside class="rider-sidebar" id="riderSidebar">
<div class="rider-sidebar-brand"><div class="rider-sidebar-brand-icon"><i class="fas fa-motorcycle"></i></div><div><div class="rider-sidebar-brand-name">Humsafar</div><div class="rider-sidebar-brand-subtitle">RIDER PARTNER</div></div></div>
<nav class="rider-sidebar-nav"><div class="rider-sidebar-section">MAIN MENU</div><a href="rider-dashboard.php" class="rider-sidebar-item <?=riderActive('rider-dashboard.php')?>"><i class="fas fa-chart-line"></i><span>Dashboard</span></a><?php if($isApproved): ?><a href="rider-orders.php" class="rider-sidebar-item <?=riderActive('rider-orders.php')?>"><i class="fas fa-receipt"></i><span>Available Orders</span></a><a href="rider-deliveries.php" class="rider-sidebar-item <?=riderActive('rider-deliveries.php')?>"><i class="fas fa-motorcycle"></i><span>My Deliveries</span></a><?php else: ?><div class="rider-sidebar-item locked"><i class="fas fa-receipt"></i><span>Available Orders</span><i class="fas fa-lock rider-sidebar-lock"></i></div><div class="rider-sidebar-item locked"><i class="fas fa-motorcycle"></i><span>My Deliveries</span><i class="fas fa-lock rider-sidebar-lock"></i></div><?php endif; ?><div class="rider-sidebar-section">ACCOUNT</div><a href="rider-earnings.php" class="rider-sidebar-item <?=riderActive('rider-earnings.php')?>"><i class="fas fa-wallet"></i><span>Earnings</span></a><a href="rider-profile.php" class="rider-sidebar-item <?=riderActive('rider-profile.php')?>"><i class="fas fa-user"></i><span>Profile</span></a><a href="rider-vehicle.php" class="rider-sidebar-item <?=riderActive('rider-vehicle.php')?>"><i class="fas fa-car"></i><span>Vehicle</span></a><a href="rider-support.php" class="rider-sidebar-item <?=riderActive('rider-support.php')?>"><i class="fas fa-headset"></i><span>Support</span></a><a href="rider-notifications.php" class="rider-sidebar-item <?=riderActive('rider-notifications.php')?>"><i class="fas fa-bell"></i><span>Notifications</span></a></nav>
<div class="rider-sidebar-bottom"><div class="rider-sidebar-profile"><div class="rider-sidebar-avatar"><?=rider_e($initials)?></div><div class="rider-sidebar-profile-info"><div class="rider-sidebar-profile-name"><?=rider_e($riderName)?></div><div class="rider-sidebar-profile-status"><?=rider_e($riderStatus)?></div></div></div><a href="rider-logout.php" class="rider-sidebar-item rider-sidebar-logout"><i class="fas fa-right-from-bracket"></i><span>Logout</span></a></div></aside>
<script>const rm=document.getElementById('riderSidebarMenu'),rs=document.getElementById('riderSidebar');if(rm&&rs)rm.onclick=()=>rs.classList.toggle('open');</script>
