<?php
require_once __DIR__ . '/../includes/config.php';
if (session_status() === PHP_SESSION_NONE) session_start();
if (empty($_SESSION['user_id']) && empty($_SESSION['customer_id'])) { header('Location: login.php'); exit; }
$userId=(int)($_SESSION['user_id']??$_SESSION['customer_id']); $orderId=(int)($_GET['order_id']??$_POST['order_id']??0); $msg=''; $err='';
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function hasCol($c,$t,$x){$s=$c->prepare("SELECT COUNT(*) n FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=?");if(!$s)return false;$s->bind_param('ss',$t,$x);$s->execute();$n=(int)$s->get_result()->fetch_assoc()['n'];$s->close();return $n>0;}
if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['submit_proof'])){
 if($orderId<=0){$err='Invalid order.';}elseif(empty($_FILES['proof']['name'])){$err='Please upload your payment screenshot.';}else{
  $f=$_FILES['proof'];$ok=['image/jpeg','image/png','image/webp'];$mime=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']);
  if($f['error']!==UPLOAD_ERR_OK||!in_array($mime,$ok,true)||$f['size']>5*1024*1024){$err='Upload a JPG, PNG or WEBP image up to 5MB.';}else{
   $s=$conn->prepare("SELECT id FROM orders WHERE id=? AND user_id=? LIMIT 1");$s->bind_param('ii',$orderId,$userId);$s->execute();$order=$s->get_result()->fetch_assoc();$s->close();
   if(!$order){$err='Order not found or you do not have access to it.';}else{
    $dir=__DIR__.'/../uploads/payment_proofs';if(!is_dir($dir))mkdir($dir,0755,true);$ext=$mime==='image/png'?'png':($mime==='image/webp'?'webp':'jpg');$name='order_'.$orderId.'_'.bin2hex(random_bytes(8)).'.'.$ext;$relative='uploads/payment_proofs/'.$name;
    if(!move_uploaded_file($f['tmp_name'],$dir.'/'.$name)){$err='Unable to save screenshot.';}else{
     $ref=trim($_POST['transaction_reference']??'');$method=trim($_POST['payment_method']??'online');
     $p=$conn->prepare("SELECT id FROM payments WHERE order_id=? ORDER BY id DESC LIMIT 1");$p->bind_param('i',$orderId);$p->execute();$existing=$p->get_result()->fetch_assoc();$p->close();
     if($existing){$q=$conn->prepare("UPDATE payments SET proof_image=?,transaction_reference=?,payment_method=?,status='pending',paid_at=NULL WHERE id=?");$pid=(int)$existing['id'];$q->bind_param('sssi',$relative,$ref,$method,$pid);}else{
      $amount=0.0;if(hasCol($conn,'orders','total_amount')){$a=$conn->prepare('SELECT total_amount FROM orders WHERE id=?');$a->bind_param('i',$orderId);$a->execute();$amount=(float)($a->get_result()->fetch_assoc()['total_amount']??0);$a->close();}elseif(hasCol($conn,'orders','total')){$a=$conn->prepare('SELECT total FROM orders WHERE id=?');$a->bind_param('i',$orderId);$a->execute();$amount=(float)($a->get_result()->fetch_assoc()['total']??0);$a->close();}
      $q=$conn->prepare("INSERT INTO payments (order_id,payment_method,provider,status,amount,transaction_reference,proof_image) VALUES (?,?,'manual','pending',?,?,?)");$q->bind_param('isdss',$orderId,$method,$amount,$ref,$relative);
     }
     if(!$q->execute()){$err='Payment could not be submitted: '.$conn->error;}else{$msg='Payment screenshot submitted successfully. Admin verification is pending.';}
     $q->close();
    }
   }
  }
 }
}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Upload Payment Proof | Humsafar</title><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"><style>*{box-sizing:border-box}body{margin:0;background:#fff8fb;font-family:Segoe UI,Arial;color:#292929}.box{max-width:650px;margin:55px auto;padding:28px;background:#fff;border:1px solid #f0dce5;border-radius:18px}.icon{width:54px;height:54px;border-radius:14px;background:#fff0f5;color:#ed0038;display:grid;place-items:center;font-size:22px}.box h1{font-size:24px;margin:14px 0 5px}.sub{color:#888;font-size:12px;margin-bottom:22px}.alert{padding:12px;border-radius:9px;font-size:11px;font-weight:700;margin-bottom:15px}.ok{background:#e7f8ed;color:#176c36}.err{background:#fff0f3;color:#a0002d}.field{margin:14px 0}.field label{display:block;font-size:10px;font-weight:800;margin-bottom:6px}.input{width:100%;height:43px;border:1px solid #e6d6dd;border-radius:9px;padding:0 12px}.upload{border:2px dashed #efcbd8;border-radius:12px;padding:25px;text-align:center;background:#fffafd}.upload i{font-size:28px;color:#ed0038}.upload p{font-size:10px;color:#888}.btn{width:100%;height:44px;border:0;border-radius:9px;background:#ed0038;color:#fff;font-weight:800;cursor:pointer}</style></head><body><div class="box"><div class="icon"><i class="fa-solid fa-receipt"></i></div><h1>Upload Payment Proof</h1><div class="sub">Order #<?=h($orderId)?> — Upload your online payment screenshot for admin verification.</div><?php if($msg):?><div class="alert ok"><i class="fa-solid fa-circle-check"></i> <?=h($msg)?></div><?php endif;?><?php if($err):?><div class="alert err"><i class="fa-solid fa-circle-exclamation"></i> <?=h($err)?></div><?php endif;?><form method="post" enctype="multipart/form-data"><input type="hidden" name="order_id" value="<?=h($orderId)?>"><div class="field"><label>Payment Method</label><select class="input" name="payment_method"><option value="online">Online Payment</option><option value="bank_transfer">Bank Transfer</option><option value="jazzcash">JazzCash</option><option value="easypaisa">Easypaisa</option></select></div><div class="field"><label>Transaction Reference (optional)</label><input class="input" name="transaction_reference" placeholder="Transaction ID / reference"></div><div class="field"><label>Payment Screenshot *</label><div class="upload"><i class="fa-solid fa-cloud-arrow-up"></i><p>JPG, PNG or WEBP — maximum 5MB</p><input type="file" name="proof" accept="image/jpeg,image/png,image/webp" required></div></div><button class="btn" name="submit_proof"><i class="fa-solid fa-paper-plane"></i> Submit for Verification</button></form></div></body></html>